### ISSUE TITLE
Room created that already exists

### ISSUE THREAD

**Issue by bludot** [bludot/ircclient#4]
after a pm this happens when a user says something. a new room with the same name is created.

**Comment by SpiredMoth** [comment]
I've had this happen without having received a PM.

A variant of this also happened in previous version where the name on the new tab was the poster of the message.

When taken together, it leads me to believe it has something to do with channel/tab focus in general.

**Comment by bludot** [comment]
I think I found the issue. I released a new version today with multiple fixes and additions. Please check it and see if it is fixed.

**Comment by SpiredMoth** [comment]
Just happened to me again with v1.1.4

**Comment by bludot** [comment]
try the latest one 1.1.6 its another attempt to fix the duplicate rooms.

**Comment by bludot** [comment]
Issue resolved
