### ISSUE TITLE
Chat log redraw on user join

### ISSUE THREAD

**Issue by SpiredMoth** [bludot/ircclient#9]
The chat log of the currently selected tab gets redrawn whenever a user joins _any_ room you're in. The newly visible chat log reflects the room with the most recent join.

[Screenshot](https://docs.google.com/drawings/d/1HlkbmUNFIVnQXmMmZJjzdnWJixXfpdC5p33Xp5C15xg/edit?usp=sharing) - Chat log is from #spp-wifi on SynIRC while the selected tab is #legendary_pokemon on SystemNet.

The chat log does at least update properly if you select another tab.

**Comment by bludot** [comment]
This has been fixed. Before it changed wether you or someone else has been joining. This has been moved to only if you are joining.
